name: Run Google Colab Notebook

on:
  workflow_dispatch:
  schedule:
    - cron: '00 13 * * *'  # Runs daily at 5:30 PM IST time

jobs:
  run_colab:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Adjust as needed

      - name: Install Google Colab CLI
        run: pip install -q colab-cli

      - name: Execute Google Colab Notebook
        run: colab --file /content/drive/MyDrive/Colab\ Notebooks/Beacon_FB_Analysis_Final.ipynb
